add default to check-env-var-param, add condition for when value is empty string

diff --git a/src/commands/check-env-var-param.yml b/src/commands/check-env-var-param.yml
--- a/src/commands/check-env-var-param.yml
+++ b/src/commands/check-env-var-param.yml
@@ -9,6 +9,7 @@ parameters:
 
   param:
     type: string
+    default: ""
     description: >
       Comma-separated list of `env_var_name`-type values; all will be
       checked to ensure they are defined. Designed to be called at the
@@ -34,18 +35,22 @@ steps:
   - run:
       name: <<parameters.command-name>>
       command: |
-        IFS="," read -ra PARAMS \<<< "<<parameters.param>>"
+        if [[ <<parameters.param>> == "" ]]; then
+          echo "No required environment variables to check; moving on"
+        else
+          IFS="," read -ra PARAMS \<<< "<<parameters.param>>"
 
-        for i in "${PARAMS[@]}"; do
-          if [[ -z "${i}" ]]; then
-            echo "ERROR: Missing environment variable {i}" >&2
+          for i in "${PARAMS[@]}"; do
+            if [[ -z "${i}" ]]; then
+              echo "ERROR: Missing environment variable {i}" >&2
 
-            if [[ -n "<<parameters.error-message>>" ]]; then
-              echo "<<parameters.error-message>>" >&2
+              if [[ -n "<<parameters.error-message>>" ]]; then
+                echo "<<parameters.error-message>>" >&2
+              fi
+
+              <<#parameters.exit-if-undefined>>exit 1<</parameters.exit-if-undefined>>
+            else
+              echo "Yes, ${i} is defined!"
             fi
-
-            <<#parameters.exit-if-undefined>>exit 1<</parameters.exit-if-undefined>>
-          else
-            echo "Yes, ${i} is defined!"
-          fi
-        done
+          done
+        fi
