multiple env var params check

diff --git a/src/commands/check-env-var-param.yml b/src/commands/check-env-var-param.yml
--- a/src/commands/check-env-var-param.yml
+++ b/src/commands/check-env-var-param.yml
@@ -1,10 +1,14 @@
 description: >
-  Check that an env-var parameter is defined, produce an error otherwise
+  Check that env-var parameters are defined, produce an error otherwise
 
 parameters:
   param:
-    type: env_var_name
-    description: Name of the environment variable to check
+    type: string
+    description: >
+      Comma-separated list of `env_var_name` type values, all will be
+      checked to ensure they are defined. Designed to be called at the
+      beginning of an orb job or command, with a value like the following:
+      `<<parameters.foo>>,<<parameters.bar>>,<<parameters.baz>`, etc.
 
   error-message:
     type: string
@@ -23,14 +27,20 @@ parameters:
 
 steps:
   - run:
-      name: Checking if $<<parameters.param>> is defined...
+      name: Checking if parameters are defined...
       command: |
-        if [[ -z "${<<parameters.param>>}" ]]; then
-          echo "ERROR: Missing environment variable <<parameters.param>>" >&2
+        IFS="," read -ra PARAMS \<<< "<<parameters.param>>"
+
+        for i in "${PARAMS[@]}"; do
+          if [[ -z "${i}" ]]; then
+          echo "ERROR: Missing environment variable {i}" >&2
+
           if [[ -n "<<parameters.error-message>>" ]]; then
             echo "<<parameters.error-message>>" >&2
           fi
+
           <<#parameters.exit-if-undefined>>exit 1<</parameters.exit-if-undefined>>
         else
-          echo "Yes, <<parameters.param>> is defined!"
+          echo "Yes, all parameters are defined!"
         fi
+        done
