Use permissions checks for bats install
* Replace the blind fallback to trying without sudo with a more complete
check whether it is required to use sudo.
* Throw an error if required permissions to run `install.sh` are not
available.
* validate bats installation by executing it

diff --git a/src/commands/install-bats.yml b/src/commands/install-bats.yml
--- a/src/commands/install-bats.yml
+++ b/src/commands/install-bats.yml
@@ -12,8 +12,18 @@ steps:
           exit 1
         fi
 
+        if [[ $EUID == 0 ]]; then
+          export SUDO=""
+        else
+          export SUDO="sudo"
+          if ! which sudo > /dev/null; then
+            echo "root access is required - install sudo or run as root"
+            exit 1
+          fi
+        fi
+
         cd bats
-        sudo ./install.sh /usr/local || \
-          ./install.sh /usr/local
+        $SUDO ./install.sh /usr/local
         cd ..
         rm -rf bats
+        bats --version
