Minor bugfixes, shellcheck.

diff --git a/src/commands/trigger-integration-tests-workflow.yml b/src/commands/trigger-integration-tests-workflow.yml
--- a/src/commands/trigger-integration-tests-workflow.yml
+++ b/src/commands/trigger-integration-tests-workflow.yml
@@ -33,17 +33,17 @@ steps:
   - run:
       name: Trigger integration test workflow
       command: |
-        VCS_TYPE=$(echo ${CIRCLE_BUILD_URL} | cut -d '/' -f 4)
-        curl -u ${<<parameters.token-variable>>}: -X POST --header "Content-Type: application/json" -d "{
-          \"branch\": \"${CIRCLE_BRANCH}\",
-          \"parameters\": <<parameters.pipeline-param-map>>
+        VCS_TYPE=$(echo "${CIRCLE_BUILD_URL}" | cut -d '/' -f 4)
+        curl -u "${CIRCLE_TOKEN}": -X POST --header "Content-Type: application/json" -d "{
+            \"branch\": \"${CIRCLE_BRANCH}\",
+            \"parameters\": <<parameters.pipeline-param-map>>
         }" "https://circleci.com/api/v2/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline" -o /tmp/curl-result.txt
         CURL_RESULT=$(cat /tmp/curl-result.txt)
 
-        if [[ $(echo $CURL_RESULT | jq -M .message) == '"Project not found"' || $(echo $CURL_RESULT | jq -M .message) == '"Permission denied"' ]]; then
-          echo "Was unable to trigger integration test workflow. API response: $(cat /tmp/curl-result.txt | jq .message)"
-          exit 1
+        if [[ $(echo "$CURL_RESULT" | jq -r .message) == "Not Found" || $(echo "$CURL_RESULT" | jq -r .message) == "Permission denied" || $(echo "$CURL_RESULT" | jq -r .message) == "Project not found" ]]; then
+            echo "Was unable to trigger integration test workflow. API response: $(cat /tmp/curl-result.txt | jq -r .message)"
+            exit 1
         else
-          echo "Pipeline triggered!"
-          cat /tmp/curl-result.txt
+            echo "Pipeline triggered!"
+            cat /tmp/curl-result.txt
         fi
