[semver:minor] #75 - Add logic to fail pipeline if API call fails. (#88)

diff --git a/src/commands/trigger-integration-tests-workflow.yml b/src/commands/trigger-integration-tests-workflow.yml
--- a/src/commands/trigger-integration-tests-workflow.yml
+++ b/src/commands/trigger-integration-tests-workflow.yml
@@ -30,11 +30,22 @@ steps:
       steps:
         - checkout
 
+  - jq/install
+
   - run:
       name: Trigger integration test workflow
       command: |
-        VCS_TYPE=$(echo ${CIRCLE_BUILD_URL} | cut -d '/' -f 4)
-        curl -u ${<<parameters.token-variable>>}: -X POST --header "Content-Type: application/json" -d "{
-          \"branch\": \"${CIRCLE_BRANCH}\",
-          \"parameters\": <<parameters.pipeline-param-map>>
-        }" "https://circleci.com/api/v2/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline"
+        VCS_TYPE=$(echo "${CIRCLE_BUILD_URL}" | cut -d '/' -f 4)
+        curl -u "${<<parameters.token-variable>>}": -X POST --header "Content-Type: application/json" -d "{
+            \"branch\": \"${CIRCLE_BRANCH}\",
+            \"parameters\": <<parameters.pipeline-param-map>>
+        }" "https://circleci.com/api/v2/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline" -o /tmp/curl-result.txt
+        CURL_RESULT=$(cat /tmp/curl-result.txt)
+
+        if [[ $(echo "$CURL_RESULT" | jq -r .message) == "Not Found" || $(echo "$CURL_RESULT" | jq -r .message) == "Permission denied" || $(echo "$CURL_RESULT" | jq -r .message) == "Project not found" ]]; then
+            echo "Was unable to trigger integration test workflow. API response: $(cat /tmp/curl-result.txt | jq -r .message)"
+            exit 1
+        else
+            echo "Pipeline triggered!"
+            echo "https://app.circleci.com/jobs/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}/$(cat /tmp/curl-result.txt | jq -r .number)"
+        fi
